platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
params:
  CONTEXT: image-build
  UNPACK_ROOTFS: true
  BASE_IMAGE_REPO: ubuntu
inputs:
- name: base-image
- name: image-build
- name: oq-bin
  path: image-build/external/oq
outputs:
- name: image
caches:
- path: cache
run:
  path: ./image-build/ci/tasks/build-image.sh
